feat: added useHover and usePopover in utils
atls/hyperion pull request #483
Opened 2023-08-21 18:38 UTC by KentCpu

2023-08-21 18:54 UTC, KentCpu commented
Задача #468 

Изменения:

- Добавил хук useHover
- Добавил хук usePopover

2023-08-24 13:50 UTC, Nelfimov requested changes

2023-08-24 13:50 UTC, Nelfimov commented on utils/use-popover/package.json
> +    "react": "18.2.0"
А как же `peerDependencies`?

2023-08-24 13:50 UTC, Nelfimov commented on utils/use-popover/package.json
> +  "license": "BSD-3-Clause",
Забыл версию.

2023-08-26 16:24 UTC, KentCpu commented
@Nelfimov 

1. Нужно ли в `use-hover` добавить peerDependencies ? В dependies уже есть пакет `react-laag`, у которого в peerDependies уже есть `react` и `react-dom`. По идее, они должны подтянутся автоматически или нет ?
2. В [задаче](https://github.com/atls/hyperion/issues/468#issuecomment-1671801214) была упомянута довольно [ситуативная утилита ](https://github.com/torin-asakura/drum-in/blob/master/ui/utils/src/helpers/capitalize.helper.ts), стоит ли ее добавить ?

2023-08-28 07:06 UTC, Nelfimov approved these changes

2023-08-28 07:06 UTC, Nelfimov commented
> Нужно ли в use-hover добавить peerDependencies ? В dependies уже есть пакет react-laag, у которого в peerDependies уже есть react и react-dom. По идее, они должны подтянутся автоматически или нет ?

Нет.

> В задаче была упомянута довольно ситуативная утилита , стоит ли ее добавить ?

Можно.

2023-08-28 10:14 UTC, TorinAsakura commented
Конфликт

2023-08-29 12:02 UTC, merged