Chore/update button peerDependencies
atls/hyperion pull request #485
Opened 2023-08-23 12:37 UTC by MakhovRoman

- Апгрейд `peerDependencies` в  `ui-parts/button` и `ui-proto/button`

2023-08-23 12:43 UTC, Nelfimov requested changes
- [ ] ошибка в чеках последнего коммита
- [x] коммит не подписан

2023-08-24 06:05 UTC, MakhovRoman commented
> * [ ]  ошибка в чеках последнего коммита
> * [ ]  коммит не подписан

- Я пытался нагуглить описание ошибки, но из самого подходящего [ответа](https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues) понял, что проблема либо с файлами node.js, либо что-то не так с [пакетами](https://bobbyhadz.com/blog/javascript-cannot-find-module-loader-js#common-causes-of-the-error).
Для меня непонятной остается причина возникновения ошибки - я пробовал откатить изменения, но ошибка сохраняется. 

- Я не совсем понял, что имелось ввиду - коммит я добавлял командой `git commit -S -m "chore: update peerDependencies"` , gpg ключ подтянулся. Или нужно было по-другом коммитить?

2023-08-24 06:12 UTC, Nelfimov commented
> > * [ ]   ошибка в чеках последнего коммита
> > * [ ]   коммит не подписан
> 
> * Я пытался нагуглить описание ошибки, но из самого подходящего [ответа](https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues) понял, что проблема либо с файлами node.js, либо что-то не так с [пакетами](https://bobbyhadz.com/blog/javascript-cannot-find-module-loader-js#common-causes-of-the-error).
>   Для меня непонятной остается причина возникновения ошибки - я пробовал откатить изменения, но ошибка сохраняется.

`yarn check` пробовал?

Так же попробуй билдить библиотеки, либо воспользуйся командой `yarn workspaces changed foreach image pack --publish --tag-policy hash-timestamp --registry some`. Там всплывет ошибка с подробным описанием.

> * Я не совсем понял, что имелось ввиду - коммит я добавлял командой `git commit -S -m "chore: update peerDependencies"` , gpg ключ подтянулся. Или нужно было по-другом коммитить?

Мой косяк, не увидел. Считай это выполнено.

2023-08-24 09:46 UTC, TorinAsakura commented
@MakhovRoman -S не нужно вводить каждый раз, в документации гитхаба есть следующая страница где описан процесс настройки автоподписи коммита

2023-08-24 10:51 UTC, MakhovRoman commented
> > > * [ ]    ошибка в чеках последнего коммита
> > > * [ ]    коммит не подписан
> > 
> > 
> > 
> > * Я пытался нагуглить описание ошибки, но из самого подходящего [ответа](https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues) понял, что проблема либо с файлами node.js, либо что-то не так с [пакетами](https://bobbyhadz.com/blog/javascript-cannot-find-module-loader-js#common-causes-of-the-error).
> >   Для меня непонятной остается причина возникновения ошибки - я пробовал откатить изменения, но ошибка сохраняется.
> 
> `yarn check` пробовал?
> 
> Так же попробуй билдить библиотеки, либо воспользуйся командой `yarn workspaces changed foreach image pack --publish --tag-policy hash-timestamp --registry some`. Там всплывет ошибка с подробным описанием.
> 
> > * Я не совсем понял, что имелось ввиду - коммит я добавлял командой `git commit -S -m "chore: update peerDependencies"` , gpg ключ подтянулся. Или нужно было по-другом коммитить?
> 
> Мой косяк, не увидел. Считай это выполнено.

Результат выполнения `yarn check`:
<details>
<summary>yarn check logs</summary>

```text
(node:71409) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
➤ YN0000: ┌ Format
➤ YN0000: └ Completed in 5s 210ms
➤ YN0000: Done in 5s 213ms
➤ YN0000: ┌ Typecheck
➤ YN0000: └ Completed in 19s 117ms
➤ YN0000: Done in 19s 117ms
➤ YN0000: ┌ Lint
➤ YN0000: └ Completed in 30s 591ms
➤ YN0000: Done in 30s 591ms

```
</details

Результат выполнения `yarn workspaces changed foreach image pack --publish --tag-policy hash-timestamp --registry some`:
<details>
<summary>yarn workspaces logs</summary>

```text
(node:71902) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[@atls-ui-admin/icon]: Process started
[@atls-ui-admin/icon]: ➤ YN0000: Workspace @atls-ui-admin/icon not allowed for package.
[@atls-ui-admin/icon]: ➤ YN0000: Done in 0s 1ms
[@atls-ui-admin/icon]: Process exited (exit code 0), completed in 0s 270ms

[@atls-ui-admin/icons]: Process started
[@atls-ui-admin/icons]: ➤ YN0000: Workspace @atls-ui-admin/icons not allowed for package.
[@atls-ui-admin/icons]: ➤ YN0000: Done in 0s
[@atls-ui-admin/icons]: Process exited (exit code 0), completed in 0s 220ms

[@atls-ui-admin/upload]: Process started
[@atls-ui-admin/upload]: ➤ YN0000: Workspace @atls-ui-admin/upload not allowed for package.
[@atls-ui-admin/upload]: ➤ YN0000: Done in 0s
[@atls-ui-admin/upload]: Process exited (exit code 0), completed in 0s 206ms

[@atls-ui-parts/card]: Process started
[@atls-ui-parts/card]: ➤ YN0000: Workspace @atls-ui-parts/card not allowed for package.
[@atls-ui-parts/card]: ➤ YN0000: Done in 0s 1ms
[@atls-ui-parts/card]: Process exited (exit code 0), completed in 0s 224ms

[@atls-ui-proto/carousel]: Process started
[@atls-ui-proto/carousel]: ➤ YN0000: Workspace @atls-ui-proto/carousel not allowed for package.
[@atls-ui-proto/carousel]: ➤ YN0000: Done in 0s
[@atls-ui-proto/carousel]: Process exited (exit code 0), completed in 0s 224ms
```
</details>

Все команды выполнял в корневом каталоге - `hyperion`. Если я все правильно понял, то запуск в корне команды `yarn install` подтягивает по цепочке установку зависимостей во всех `workspace` ?

Пытался связать ошибку с `DeprecationWarning`, но [найденный способ ](https://github.com/webpack/webpack/issues/11350#issuecomment-677470860) не помог. Я зашел в тупик, не знаю куда смотреть, чтобы решить эту проблему. По-идее, даже если у меня криво встали зависимости, то на проверки в `workflows` это никак не должно было повлиять?

2023-08-24 13:16 UTC, TorinAsakura commented
> > > > * [ ]     ошибка в чеках последнего коммита
> > > > * [ ]     коммит не подписан
> > > 
> > > 
> > > 
> > > * Я пытался нагуглить описание ошибки, но из самого подходящего [ответа](https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues) понял, что проблема либо с файлами node.js, либо что-то не так с [пакетами](https://bobbyhadz.com/blog/javascript-cannot-find-module-loader-js#common-causes-of-the-error).
> > >   Для меня непонятной остается причина возникновения ошибки - я пробовал откатить изменения, но ошибка сохраняется.
> > 
> > 
> > `yarn check` пробовал?
> > Так же попробуй билдить библиотеки, либо воспользуйся командой `yarn workspaces changed foreach image pack --publish --tag-policy hash-timestamp --registry some`. Там всплывет ошибка с подробным описанием.
> > > * Я не совсем понял, что имелось ввиду - коммит я добавлял командой `git commit -S -m "chore: update peerDependencies"` , gpg ключ подтянулся. Или нужно было по-другом коммитить?
> > 
> > 
> > Мой косяк, не увидел. Считай это выполнено.
> 
> Результат выполнения `yarn check`:
> 
> yarn check logs
> Результат выполнения `yarn workspaces changed foreach image pack --publish --tag-policy hash-timestamp --registry some`:
> yarn workspaces logs
> Все команды выполнял в корневом каталоге - `hyperion`. Если я все правильно понял, то запуск в корне команды `yarn install` подтягивает по цепочке установку зависимостей во всех `workspace` ?
> 
> Пытался связать ошибку с `DeprecationWarning`, но [найденный способ ](https://github.com/webpack/webpack/issues/11350#issuecomment-677470860) не помог. Не знаю куда смотреть, чтобы решить эту проблему. По-идее, даже если у меня криво встали зависимости, то на проверки в `workflows` это никак не должно было повлиять?

1. Если тебе нужно ре-ревью - перезапроси его нажав на соответствующую кнопку в сайдбаре
2. Warning - не ошибка, она ничего не ломает, а лишь предупреждает, на неё не стоит обращать внимания
3. yarn выполненный в корне запускает установку всех зависимостей по цепочке, да
4. https://github.com/atls/hyperion/actions/runs/5951390633/job/16141112732?pr=485#step:4:151 - ты не закоммитил изменения своего yarn.lock

2023-08-24 15:18 UTC, MakhovRoman commented
> > > > > * [ ]      ошибка в чеках последнего коммита
> > > > > * [ ]      коммит не подписан
> > > > 
> > > > 
> > > > 
> > > > * Я пытался нагуглить описание ошибки, но из самого подходящего [ответа](https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues) понял, что проблема либо с файлами node.js, либо что-то не так с [пакетами](https://bobbyhadz.com/blog/javascript-cannot-find-module-loader-js#common-causes-of-the-error).
> > > >   Для меня непонятной остается причина возникновения ошибки - я пробовал откатить изменения, но ошибка сохраняется.
> > > 
> > > 
> > > `yarn check` пробовал?
> > > Так же попробуй билдить библиотеки, либо воспользуйся командой `yarn workspaces changed foreach image pack --publish --tag-policy hash-timestamp --registry some`. Там всплывет ошибка с подробным описанием.
> > > > * Я не совсем понял, что имелось ввиду - коммит я добавлял командой `git commit -S -m "chore: update peerDependencies"` , gpg ключ подтянулся. Или нужно было по-другом коммитить?
> > > 
> > > 
> > > Мой косяк, не увидел. Считай это выполнено.
> > 
> > 
> > Результат выполнения `yarn check`:
> > yarn check logs
> > Результат выполнения `yarn workspaces changed foreach image pack --publish --tag-policy hash-timestamp --registry some`:
> > yarn workspaces logs
> > Все команды выполнял в корневом каталоге - `hyperion`. Если я все правильно понял, то запуск в корне команды `yarn install` подтягивает по цепочке установку зависимостей во всех `workspace` ?
> > Пытался связать ошибку с `DeprecationWarning`, но [найденный способ ](https://github.com/webpack/webpack/issues/11350#issuecomment-677470860) не помог. Не знаю куда смотреть, чтобы решить эту проблему. По-идее, даже если у меня криво встали зависимости, то на проверки в `workflows` это никак не должно было повлиять?
> 
> 1. Если тебе нужно ре-ревью - перезапроси его нажав на соответствующую кнопку в сайдбаре
> 2. Warning - не ошибка, она ничего не ломает, а лишь предупреждает, на неё не стоит обращать внимания
> 3. yarn выполненный в корне запускает установку всех зависимостей по цепочке, да
> 4. https://github.com/atls/hyperion/actions/runs/5951390633/job/16141112732?pr=485#step:4:151 - ты не закоммитил изменения своего yarn.lock

Спасибо, все сработало

2023-08-24 18:37 UTC, Nelfimov approved these changes

2023-08-24 20:55 UTC, TorinAsakura approved these changes

2023-08-25 16:58 UTC, merged