Грейд зависимостей text-transform, upload, sidebar, portal, modal
atls/hyperion pull request #496
Opened 2023-08-30 13:17 UTC by AlinaLaniuk

**Таска: https://github.com/atls/hyperion/issues/492**

Обновила зависимости @atls-ui-parts и @atls-ui-proto у text-transform, upload, sidebar, portal, modal под актуальные пакеты

- только жесткие версии
- пакеты @emotion либо оставила, либо повысила до версии 11.9.х.

Ошибки не падают, в сторибуке вроде все работает.

2023-08-30 14:15 UTC, SlumberyDude commented
@AlinaLaniuk Если считаешь, что все, то надо зареквестить у кого-нибудь ревью в правом верхнем углу.

2023-08-30 14:24 UTC, AlinaLaniuk commented
@SlumberyDude а есть какие-то требования к оформлению? https://github.com/atls/convention/wiki/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-GitHub
тут вот ничего конкретного не указано. я вроде оформила, как понимаю)
и подскажи, плиз, кого просить в ревьюверы? в конвенции сказано, что либо ментора (у меня его либо нет, либо я не знаю, кто это), либо Андрея. но в чате я что-то еще видела про то, что надо Никиту звать.

2023-08-30 14:28 UTC, SlumberyDude commented
@AlinaLaniuk Да, в правилах явно требования оформления PR не указаны, там есть по issue. Но так удобнее, когда видно, кто в данный момент занимается этим PR, что-то вроде правил хорошего тона, облегчает работу.

2023-08-31 05:28 UTC, Nelfimov requested changes
Все ок, принимаю.

Сделай пожалуйста еще одно маленькое дело - чтобы версии твоих обновленных пакетов повысились автоматом и запаблились в npmjs, сделай какие то минорные правки в коде обновленных пакетов. Например, можешь поменять местам строки или интерфейсы переформатировать.

2023-08-31 06:34 UTC, AlinaLaniuk commented
@Nelfimov добавила изменения.
А можешь плиз в двух словах, почему это так работает? Почему недостаточно изменений в package.json для того, чтобы версии подтянулись?

2023-08-31 06:46 UTC, Nelfimov requested changes
Обрати внимание:
Достаточно одного изменения в коде пакета. Изменение импорта, добавление пробелов в конце - не сработает, потому что `yarn format` затем приведет все к одному стандарту. А вот изменение внутри объекта порядка аттрибутов или изменение порядка функций - норм.

> А можешь плиз в двух словах, почему это так работает? Почему недостаточно изменений в package.json для того, чтобы версии подтянулись?

Так работает наш github actions - смотрит на изменения в коде. Если есть - инкрементирует версию в `package.json` и публикует новый пакет в npmjs.

2023-08-31 06:46 UTC, Nelfimov commented on ui-parts/portal/src/portal.component.tsx
> +import { createPortal }      from 'react-dom'
Порядок импортов будет изменен при `yarn format`. Надо другое изменение.

2023-08-31 06:46 UTC, Nelfimov commented on ui-parts/sidebar/src/container/container.styles.ts
> +  height: '100%',
вот это норм изменение.

2023-08-31 09:49 UTC, Nelfimov approved these changes

2023-08-31 22:48 UTC, TorinAsakura commented
конфликт

2023-09-01 07:38 UTC, AlinaLaniuk commented
> конфликт

исправила

2023-09-05 21:17 UTC, TorinAsakura commented
где? я всё ещё вижу конфликты

2023-09-05 21:20 UTC, TorinAsakura approved these changes

2023-09-06 07:35 UTC, merged