chore: upgrade dependencies ui-parts core, ui-proto core divider
atls/hyperion pull request #497
Opened 2023-08-30 16:44 UTC by aliceinapple

#### Апгрейд зависимостей @atls-ui-parts и @atls-ui-proto у компонентов divider и core

- пакеты @emotion оставила на версии 11.9.х,
- только жесткие версии,
- yarn check проходит без ошибок, 
- версии обновлены до максимально последних, 
- истории design с компонентом работают.

2023-08-31 05:20 UTC, Nelfimov requested changes
Все ок, принимаю.

Сделай пожалуйста еще одно маленькое дело - чтобы версии твоих обновленных пакетов повысились автоматом и запаблились в npmjs, сделай какие то минорные правки в коде обновленных пакетов. Например, можешь поменять местам строки или интерфейсы переформатировать.

2023-08-31 05:24 UTC, aliceinapple commented
> Все ок, принимаю.
> 
> Сделай пожалуйста еще одно маленькое дело - чтобы версии твоих обновленных пакетов повысились автоматом и запаблились в npmjs, сделай какие то минорные правки в коде обновленных пакетов. Например, можешь поменять местам строки или интерфейсы переформатировать.

Хорошо, вечером, когда буду дома, сделаю.

2023-08-31 15:51 UTC, Nelfimov approved these changes

2023-08-31 22:47 UTC, TorinAsakura commented
конфликт

2023-09-01 05:26 UTC, aliceinapple commented
> конфликт

Исправлю

2023-09-05 21:22 UTC, TorinAsakura requested changes
Всё ок, но, чеки нужно пофиксить

2023-09-05 22:06 UTC, TorinAsakura approved these changes

2023-09-06 16:16 UTC, merged