chore: update dependencies hidden-input, events-state
atls/hyperion pull request #510
Opened 2023-10-23 10:51 UTC by absolemDev

2023-10-23 11:05 UTC, absolemDev commented
Хьюстон, у нас проблемы!

2023-10-23 12:00 UTC, absolemDev commented
@Nelfimov, ошибка на шаге Install `The lockfile would have been modified by this install, which is explicitly forbidden.`. Что я еще не обновил?

2023-10-23 12:46 UTC, Nelfimov commented
> @Nelfimov, ошибка на шаге Install `The lockfile would have been modified by this install, which is explicitly forbidden.`. Что я еще не обновил?

локально запусти
- `yarn`
- `yarn check`

После этого проверь есть ли что закоммитить. Если да - коммить.

2023-10-23 13:27 UTC, absolemDev commented
@Nelfimov, расскажи подробней про `storybook`, как я должен проверить функционал компонента в нем. Я не работал раньше со `storybook`.

2023-10-23 13:43 UTC, Nelfimov commented
> @Nelfimov, расскажи подробней про `storybook`, как я должен проверить функционал компонента в нем. Я не работал раньше со `storybook`.

Посмотри в соседние компоненты - много где есть `...stories.ts` - по этим файлам `storybook` проходится и составляет предпросмотр компонентов. Например, можешь посмотреть наш сторибук в продакшене: https://ui.atls.design

Поэтому задание ссылается на сторибук - если там есть эти файлы, то надо убедиться что локальный сторибук подхватывает компоненты и рендерит их, а она работают.

Если этого нет, остается вариант с параллельным тестированием - на одной странице в тестовом проекте развернуть оба компонента - один из npmjs.com, а другой - твоя доработка. И сравнить их.

2023-10-23 17:26 UTC, Nelfimov requested changes
И еще нюанс репозитория - поменяй что то в самом коде пакетов где изменил версии - так мы сможем запустить экшн по обновлению на `npmjs.com`. Изменения в коде могут быть любые - от перестановки "слагаемых", пропсов до переименования переменных. Главное - аккуратно.

2023-10-23 17:26 UTC, Nelfimov commented on ui-parts/events-state/package.json
> +    "react": "18.2.0"
Тут поправил, а `peer`?

2023-10-23 17:26 UTC, Nelfimov commented on ui-parts/hidden-input/package.json
> +    "react": "18.2.0"
А `peer`?

2023-10-23 17:57 UTC, absolemDev commented
- `yarn check` отрабатывает без ошибок;
- версии обновлены до максимально последних;
- параллельное тестирование компоненты проходят.

2023-10-24 04:18 UTC, absolemDev commented on ui-parts/events-state/package.json
> +    "react": "18.2.0"
Поправил

2023-10-24 04:18 UTC, absolemDev commented on ui-parts/hidden-input/package.json
> +    "react": "18.2.0"
Поправил

2023-10-24 05:21 UTC, Nelfimov approved these changes

2023-10-24 10:50 UTC, TorinAsakura requested changes

2023-10-24 10:50 UTC, TorinAsakura commented on ui-proto/theme/README.md
> +import { GlobalStyles }                          from './global.styles'  локальные cтили подпроект
что-то с комментом

2023-10-24 10:50 UTC, TorinAsakura commented on ui-proto/theme/README.md
> +import { robotoRegular } from './fonts' // импортированные шрифты
полагаю этот коммент тут лишний

2023-10-24 11:38 UTC, absolemDev commented on ui-proto/theme/README.md
> +import { GlobalStyles }                          from './global.styles'  локальные cтили подпроект
Поправил

2023-10-24 11:38 UTC, absolemDev commented on ui-proto/theme/README.md
> +import { robotoRegular } from './fonts' // импортированные шрифты
Поправил

2023-10-24 14:54 UTC, TorinAsakura approved these changes

2023-10-24 14:54 UTC, merged