feat: add locales generator
atls/hyperion pull request #544
Opened 2024-01-31 13:49 UTC by FrankJaskon

2024-01-31 13:57 UTC, Nelfimov requested changes
Посмотри так же посильно ли будет сделать тесты для этого пакета. Так же обязательно убедись что у тебя актуальный мастер-база - там обновились флоу

2024-01-31 13:57 UTC, Nelfimov commented on generators/locales/package.json
> +  "version": "0.0.1",
стартовая версия 0.0.0

2024-01-31 13:57 UTC, Nelfimov commented on generators/locales/package.json
> +  "publishConfig": {
посмотри как в соседних пакетах конфиг сделан

2024-01-31 13:57 UTC, Nelfimov commented on generators/locales/src/process-directory/process-directory.ts
> +/* eslint-disable */
что именно отключил?

2024-01-31 14:32 UTC, FrankJaskon commented
@Nelfimov 

> Посмотри так же посильно ли будет сделать тесты для этого пакета.

Чот пока даже никаких идей, что мы можем протестировать.

2024-01-31 14:33 UTC, TorinAsakura commented
@FrankJaskon - получить название объекта
- передать его в качестве аргумента для нового объекта в файле

Это как пример

2024-01-31 15:34 UTC, Nelfimov requested changes
давай проверим работоспособность еще так:
- в корне проекта делаем `postinstall`
- в него закладываем `yarn workspaces foreach changed ...` и выполняем твой скрипт

2024-02-01 07:33 UTC, FrankJaskon commented
@Nelfimov 

> давай проверим работоспособность еще так:
> * в корне проекта делаем `postinstall`
> * в него закладываем `yarn workspaces foreach changed ...` и выполняем твой скрипт

<details>

![image](https://github.com/atls/hyperion/assets/84450082/0dcec48b-f1f3-437a-8249-5ad8dfe79f66)

</details>

2024-02-01 07:40 UTC, Nelfimov commented
Этот скрипт следит за изменениями в воркспейсах. Если изменения есть - запускает то что ему скажешь.

Наша цель - сделать постинсталл скрипт, который будет срабатывать при запуске `yarn` в корне проекта, который будет просматривать изменения. Где изменения были, будет искать переводы и экстрактить их.

Важно помнить, что помимо воркспейсов с фронтом у нас есть и бэк, где переводы не нужны.

Тут есть пример использования этого скрипта: https://github.com/atls/tools#проверка-проекта-на-ошибки

2024-02-01 07:41 UTC, Nelfimov requested changes
проверить работу из корня

2024-02-01 07:51 UTC, FrankJaskon commented
@Nelfimov 

> Этот скрипт следит за изменениями в воркспейсах. Если изменения есть - запускает то что ему скажешь.
> Наша цель - сделать постинсталл скрипт, который будет срабатывать при запуске `yarn` в корне проекта, который будет просматривать изменения. Где изменения были, будет искать переводы и экстрактить их.
> Важно помнить, что помимо воркспейсов с фронтом у нас есть и бэк, где переводы не нужны.
> Тут есть пример использования этого скрипта: [https://github.com/atls/tools#проверка-проекта-на-ошибки](https://github.com/atls/tools#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-%D0%BD%D0%B0-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8)

Никит, подскажи, пожалуйста, я пока не могу понять как аргументы в скрипт будут пробрасываться в зависимости от того, где именно у нас произошли изменения?

Как он будет определять где генерировать общую локаль, которая будет собирать в себя только входящие в энтрипоинт переводы?

2024-02-01 08:54 UTC, Nelfimov commented
Попробуй поиграй с этим скриптом, либо его аналогом - `yarn workspaces foreach...`. Например, `yarn workspaces foreach prepack`.

Этот скрипт пройдется по всем пакетам, и где найдет этот скрипт - запустит его. Ты можешь так же поступить с твоим скриптом - положить его в энтрипоинт фронтовых клиентов, а затем в корень добавить постинсталл

2024-02-01 10:06 UTC, FrankJaskon commented
@Nelfimov 

Попробовал оба скрипта в лабе:

`"postinstall": "yarn workspaces changed foreach --parallel run generate-locales"` - отрабатывает нормально. 

Если изменения внутри энтрипоинта, то пересобирает переводы только для этого энтрипоинта. Если изменения, например, в `ui`, то пересобирает переводы для всех энтрипоинтов(т.к все энтрипоинты зависят от ui). Если изменения, например, в `gateway`, то скрипты генерации переводов не вызываются вовсе.

`yarn workspaces foreach` - пересобирает все переводы при каждом вызове.

2024-02-01 10:08 UTC, Nelfimov commented
Для начала нам достаточно. Дополняй ридми и на ревью

2024-02-01 13:27 UTC, Nelfimov approved these changes
поправь и запрашивай дальше ревью

2024-02-01 13:27 UTC, Nelfimov commented on generators/locales/package.json
> +  "typings": "dist/index.d.ts",
вот это лишнее - у тебя это уже указано в `publishConfig`

2024-02-01 16:58 UTC, TorinAsakura requested changes
В остальном всё довольно неплохо

2024-02-01 16:58 UTC, TorinAsakura commented on generators/locales/src/process-directory/process-directory.ts
> +    console.log('No directory ', startPath)
такие штуки нужно отдавать через console.error

2024-02-02 09:53 UTC, TorinAsakura approved these changes

2024-02-02 09:54 UTC, merged