feat(utils): use-outside-click-hook
atls/hyperion pull request #578
Opened 2024-09-19 13:09 UTC by oksssvv

2024-09-19 13:13 UTC, Nelfimov requested changes

2024-09-19 13:13 UTC, Nelfimov commented on utils/use-outside-click/package.json
> +  "main": "./src/index.ts",
сюда тоже `exports`

2024-09-19 13:14 UTC, Amiditin commented on utils/use-outside-click/src/use-outside-click.hook.ts
> +  const ref = useRef<HTMLDivElement>(null)
Привязка к `div` элементу будет, нужно что то универсальное, мб `HTMLElement` подойдет

2024-09-20 09:07 UTC, Amiditin approved these changes

2024-09-20 09:10 UTC, Nelfimov approved these changes

2024-09-20 09:11 UTC, merged